rest:
  - resource: !secret nomicsapi
    scan_interval: 10
    sensor:
      ### Ethereum Cryptocurency
      - name: "Crypto - ETH"
        json_attributes_path: "$.[1]"
        value_template: "{{ value_json[1].price | round(4) }}"
        unit_of_measurement: "USD"
        json_attributes:
          - name
          - symbol
          - price
          - logo_url
          - rank
          - high
          - high_timestamp
          - market_cap
          - first_trade
      - name: "ETH Tf 1 Hr"
        json_attributes_path: "$.[1].1h"
        unit_of_measurement: "USD"
        value_template: '{{ value_json[1]["1h"]["price_change"] | round(4) }}'
        json_attributes:
          - price_change_pct
      - name: "ETH Tf 1 D"
        json_attributes_path: "$.[1].1d"
        unit_of_measurement: "USD"
        value_template: '{{ value_json[1]["1d"]["price_change"] | round(4) }}'
        json_attributes:
          - price_change_pct
      - name: "ETH Tf 7 D"
        json_attributes_path: "$.[1].7d"
        unit_of_measurement: "USD"
        value_template: '{{ value_json[1]["7d"]["price_change"] | round(4) }}'
        json_attributes:
          - price_change_pct
      - name: "ETH Tf 30 D"
        json_attributes_path: "$.[1].30d"
        unit_of_measurement: "USD"
        value_template: '{{ value_json[1]["30d"]["price_change"] | round(4) }}'
        json_attributes:
          - price_change_pct